lang: en

root_dir: .
exp_dir: !ref <root_dir>/exp_en
results_summary_dir: !ref <exp_dir>/results_summary/eval_post_en

datasets: !include:../datasets.yaml   # we will select the correct subset of the datasets according to the chosen language at run time

eval_steps:  # all metrics in this list will be computed in the evaluation. Remove entry to skip
  privacy:
    - asv

anon_data_suffix: anon  # suffix for dataset to signal that it is anonymized
eval_data_dir: !ref <root_dir>/results_<lang>/formatted_data/anon_ims_sttts_pc_whisper_<lang>

privacy:
  asv:
    model_dir: models/asv_eval_ecapa_anon  # path to existing ASV model or output for trained ASV model
    vec_type: ecapa  # ecapa or xvector

    training:
      anon: true  # true or false, depending on whether the training data for the ASV is anonymized or original
      train_data_dir: !ref <root_dir>/results_<lang>/formatted_data/anon_ims_sttts_pc_whisper_<lang>/train-clean-360_part_anon  # path to original or anonymized training data for ASV
      train_config: evaluation/privacy/asv/asv_train/hparams/train_ecapa_tdnn_small_ft.yaml
      finetuning: true # true (ft) or false (scratch)
      pretrained_model: !ref models/asv_eval_pre_<privacy[asv][vec_type]>  # path to pretrained model, only used for finetuning
      lr: 0.01
      epochs: 10
      batch_size: 256
      num_utt: ALL  # ALL or specific number, number of utterances per speaker
      utt_selection: spk-diverse-sess  # select utterances per speaker and session (spk-sess), per speaker and randomly across all sessions (spk-random), per speaker and balanced across sessions (spk-diverse-sess)
      num_spk: ALL  # ALL or specific number, number of speakers
      retrain: false  # retrain in any case (true) or skip training if model exists (false)

    evaluation:
      results_dir: !ref <privacy[asv][model_dir]>  # path to save evaluation results
      distance: cosine  # cosine or plda
      plda:   # ignored if distance is not plda
        model_dir: null  # path to trained PLDA or output of PLDA training
        train_data_dir: null # path to PLDA training data
        anon: true  # trained on anonymized (true) or original (false) data
