lang: en

root_dir: .
exp_dir: !ref <root_dir>/exp_<lang>
results_summary_dir: !ref <exp_dir>/results_summary/eval_pre_<lang>_mms

datasets: !include:../datasets.yaml   # we will select the correct subset of the datasets according to the chosen language at run time

eval_steps:  # all metrics in this list will be computed in the evaluation. Remove entry to skip
  utility:
    - asr

anon_data_suffix: anon  # suffix for dataset to signal that it is anonymized
eval_data_dir: !ref <root_dir>/results_<lang>/formatted_data/anon_ims_sttts_pc_whisper_<lang>
  # path to anonymized evaluation data in kaldi format, e.g. <eval_data_dir>/libri_test_enrolls/wav.scp etc.

utility:
  asr:
    backend: mms
    model_name: asr_pre_mms  # name for ASR model
    model_dir: !ref models/asr_eval_pre_<utility[asr][backend]>
    libri_dir: null

    evaluation:
      model_dir: !ref models/asr_eval_pre_<utility[asr][backend]>
      model_path: !ref <utility[asr][evaluation][model_dir]>
      model_url: !ref <utility[asr][evaluation][model_dir]>
      eval_batchsize: 2 # eval_batchsize(32g)=3 ->9h eval_batchsize=2->12h eval_batchsize(12GB)=1->24h
      results_dir: !ref <exp_dir>/<utility[asr][model_name]>
      recognizer: !ref <utility[asr][backend]>
      lang: !ref <lang>

