de:
  - name: mls-german_dev
    data: mls-german
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: mls-german_test
    data: mls-german
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-de_dev
    data: cv-de
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-de_test
    data: cv-de
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
en:
  - name: libri_dev
    data: libri
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: libri_test
    data: libri
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: vctk_dev
    data: vctk
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f_all, trials_m_all ]
  - name: vctk_test
    data: vctk
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f_all, trials_m_all ]
  - name: cv-en_dev
    data: cv-en
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-en_test
    data: cv-en
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
es:
  - name: mls-spanish_dev
    data: mls-spanish
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: mls-spanish_test
    data: mls-spanish
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-es_dev
    data: cv-es
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-es_test
    data: cv-es
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
fr:
  - name: mls-french_dev
    data: mls-french
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: mls-french_test
    data: mls-french
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-fr_dev
    data: cv-fr
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-fr_test
    data: cv-fr
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
it:
  - name: mls-italian_dev
    data: mls-italian
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: mls-italian_test
    data: mls-italian
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-it_dev
    data: cv-it
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-it_test
    data: cv-it
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
nl:
    - name: mls-dutch_dev
      data: mls-dutch
      set: dev
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
    - name: mls-dutch_test
      data: mls-dutch
      set: test
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
    - name: cv-nl_dev
      data: cv-nl
      set: dev
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
    - name: cv-nl_test
      data: cv-nl
      set: test
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
pl:
    - name: cv-pl_dev
      data: cv-pl
      set: dev
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
    - name: cv-pl_test
      data: cv-pl
      set: test
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
pt:
  - name: mls-portuguese_dev
    data: mls-portuguese
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: mls-portuguese_test
    data: mls-portuguese
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-pt_dev
    data: cv-pt
    set: dev
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
  - name: cv-pt_test
    data: cv-pt
    set: test
    enrolls: [ enrolls ]
    trials: [ trials_f, trials_m ]
ru:
    - name: cv-ru_dev
      data: cv-ru
      set: dev
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]
    - name: cv-ru_test
      data: cv-ru
      set: test
      enrolls: [ enrolls ]
      trials: [ trials_f, trials_m ]